"""initial

Revision ID: 8fbf8959242f
Revises: 
Create Date: 2026-09-24 21:37:23.444457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbf8959242f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='operator', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('vendor_tax_id', sa.String(length=14), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'po_number', name='uq_purchase_orders_client_po')
    )
    op.create_index('ix_purchase_orders_client_id', 'purchase_orders', ['client_id'], unique=False)
    op.create_index('ix_purchase_orders_loaded_at', 'purchase_orders', ['loaded_at'], unique=False)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_purchase_orders_vendor_tax_id', 'purchase_orders', ['vendor_tax_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('conferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=14), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conferences_checked_at', 'conferences', ['checked_at'], unique=False)
    op.create_index('ix_conferences_client_id', 'conferences', ['client_id'], unique=False)
    op.create_index('ix_conferences_result', 'conferences', ['result'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=3), server_default='0', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('item_created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line', name='uq_purchase_order_items_po_line')
    )
    op.create_index('ix_purchase_order_items_po_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_order_items_po_material', 'purchase_order_items', ['purchase_order_id', 'material'], unique=False)
    op.create_table('conference_divergences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conference_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('item_line', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('expected', sa.String(length=255), nullable=True),
    sa.Column('received', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conference_divergences_conference_id', 'conference_divergences', ['conference_id'], unique=False)
    # ### end Alembic commands ###

    # seed: clientes
    op.execute("""
        INSERT INTO clients (id, name, format_type) VALUES
        ('alfa',  'Alfa Energia',       'json_nested'),
        ('beta',  'Beta Alimentos',     'csv_dual'),
        ('gama',  'Gama Logística',     'flat_json'),
        ('delta', 'Delta Distribuição', 'split_json')
    """)

    # seed: usuário admin padrão (senha: admin123 — trocar em produção)
    op.execute("""
        INSERT INTO users (id, username, email, hashed_password, role, active)
        VALUES (
            'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
            'admin',
            'admin@v360.com',
            '$2b$12$m/O6sDLIuu8y0eFScco1mOxLnRiQjDo4f23Snml9uqT4YRgs8mMAK',
            'admin',
            true
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conference_divergences_conference_id', table_name='conference_divergences')
    op.drop_table('conference_divergences')
    op.drop_index('ix_purchase_order_items_po_material', table_name='purchase_order_items')
    op.drop_index('ix_purchase_order_items_po_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_conferences_result', table_name='conferences')
    op.drop_index('ix_conferences_client_id', table_name='conferences')
    op.drop_index('ix_conferences_checked_at', table_name='conferences')
    op.drop_table('conferences')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_purchase_orders_vendor_tax_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_loaded_at', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_client_id', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
